/**
 * Top 100 most popular Google Fonts (by usage).
 * Used for autocomplete in the brand charter font picker.
 */
export const GOOGLE_FONTS_LIST: string[] = [
  "Roboto",
  "Open Sans",
  "Noto Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Roboto Condensed",
  "Inter",
  "Oswald",
  "Raleway",
  "Nunito",
  "Nunito Sans",
  "Ubuntu",
  "Roboto Mono",
  "Rubik",
  "Playfair Display",
  "Lora",
  "Merriweather",
  "PT Sans",
  "Kanit",
  "Work Sans",
  "Fira Sans",
  "Quicksand",
  "Barlow",
  "Mulish",
  "DM Sans",
  "IBM Plex Sans",
  "Noto Serif",
  "Manrope",
  "Outfit",
  "Josefin Sans",
  "Libre Baskerville",
  "Libre Franklin",
  "Cormorant Garamond",
  "Space Grotesk",
  "Crimson Text",
  "Source Sans 3",
  "Karla",
  "Archivo",
  "Cabin",
  "Bitter",
  "Exo 2",
  "Comfortaa",
  "Abel",
  "Fjalla One",
  "Vollkorn",
  "Spectral",
  "EB Garamond",
  "Assistant",
  "Lexend",
  "Bebas Neue",
  "Prompt",
  "Signika",
  "Catamaran",
  "Dancing Script",
  "Pacifico",
  "Shadows Into Light",
  "Satisfy",
  "Great Vibes",
  "Caveat",
  "Sacramento",
  "Permanent Marker",
  "Lobster",
  "Righteous",
  "Philosopher",
  "Sora",
  "Plus Jakarta Sans",
  "Red Hat Display",
  "Jost",
  "Albert Sans",
  "Bricolage Grotesque",
  "Urbanist",
  "Figtree",
  "Geist",
  "Instrument Sans",
  "Onest",
  "Wix Madefor Display",
  "Atkinson Hyperlegible",
  "Chivo",
  "Overpass",
  "Titillium Web",
  "Asap",
  "Noto Sans Display",
  "Varela Round",
  "Yanone Kaffeesatz",
  "Arvo",
  "Abril Fatface",
  "Cardo",
  "Old Standard TT",
  "Domine",
  "Fraunces",
  "DM Serif Display",
  "Tenor Sans",
  "Space Mono",
  "JetBrains Mono",
  "Inconsolata",
  "Fira Code",
  "Source Code Pro",
  "Cormorant",
  "Bodoni Moda",
  "Mate",
];
