export const LINKEDIN_TIPS = [
  { text: "Les 210 premiers caractères décident de tout. 60-70% des lecteur·ices ne cliquent jamais 'voir plus'.", source: "Algorithm InSights 2025" },
  { text: "Les commentaires pèsent 8x plus que les likes dans l'algorithme. Pose des questions qui appellent des réponses longues.", source: "van der Blom 2025" },
  { text: "La 'Golden Hour' : les 60-90 premières minutes sont décisives. Un bon démarrage = portée x3.", source: "Algorithm InSights 2025" },
  { text: "Le dwell time (temps passé à lire) est un signal silencieux mais très puissant. Le storytelling qui tient en haleine performe.", source: "LinkedIn Engineering 2025" },
  { text: "Les liens externes coûtent ~60% de distribution. Mets-les en commentaire.", source: "van der Blom 2025" },
  { text: "Le contenu IA non retravaillé subit -43% d'engagement. Le ton incarné est non-négociable.", source: "Socialinsider 2025" },
  { text: "Sweet spot engagement : 1 300-1 900 caractères. Les posts sous 500 car. perdent 35% d'engagement.", source: "AuthoredUp 2025" },
  { text: "3-5 hashtags max et de niche. LinkedIn détecte les sujets sémantiquement maintenant.", source: "van der Blom 2025" },
  { text: "Un post LinkedIn peut vivre 2-3 semaines. Privilégie le contenu evergreen qui génère des conversations.", source: "Hootsuite 2025" },
  { text: "Réponds aux commentaires dans les 30 premières minutes. Ça relance l'algorithme.", source: "Closely 2025" },
  { text: "Profil personnel = 561% plus de reach que page entreprise. Publie en ton nom.", source: "Ordinal 2026" },
  { text: "Ne publie pas 2 posts en moins de 18-24h. Le nouveau tue la portée de l'ancien.", source: "AuthoredUp 2025" },
  { text: "Le contenu expert et de niche est valorisé par l'algo. La cohérence thématique construit l'autorité.", source: "Algorithm InSights 2025" },
  { text: "72% du trafic LinkedIn vient du mobile. Aère ton texte : paragraphes courts, sauts de ligne.", source: "LinkedIn 2025" },
  { text: "Meilleurs jours : mardi, mercredi, jeudi. Meilleures heures : 8h-9h et 14h-15h.", source: "Buffer 2025" },
];

export const LINKEDIN_TEMPLATES_UI = [
  { id: "enquete_decryptage", emoji: "🔍", label: "Enquête / Décryptage", desc: "Analyse de fond, angle original" },
  { id: "test_grandeur_nature", emoji: "🧪", label: "Test grandeur nature", desc: "J'ai testé X, verdict honnête" },
  { id: "coup_de_gueule", emoji: "😤", label: "Coup de gueule engagé", desc: "Frustration constructive" },
  { id: "mythe_deconstruction", emoji: "💥", label: "Mythe à déconstruire", desc: "Challenge une croyance populaire" },
  { id: "storytelling_lecon", emoji: "📖", label: "Storytelling + leçon", desc: "Parcours, échec, déclic" },
  { id: "histoire_cliente", emoji: "✨", label: "Histoire cliente", desc: "Avant/après, transformation" },
  { id: "surf_actu", emoji: "📰", label: "Surf sur l'actu", desc: "Tendance + angle expert" },
  { id: "regard_philosophique", emoji: "🧠", label: "Regard philosophique", desc: "Réflexion profonde, style France Culture" },
  { id: "conseil_contre_intuitif", emoji: "🔄", label: "Conseil contre-intuitif", desc: "À contre-courant, argumenté" },
  { id: "before_after", emoji: "📊", label: "Before/After", desc: "Contraste frappant, preuve" },
  { id: "build_in_public", emoji: "🏗️", label: "Build in public", desc: "Coulisses, honnêteté radicale" },
  { id: "identification_quotidien", emoji: "🙋", label: "Identification", desc: "\"C'est trop moi !\"" },
  { id: "contenu_lancement", emoji: "🚀", label: "Contenu de lancement", desc: "Vente douce et éthique" },
];
