import { beforeEach, expect, it, vi } from "vitest";
import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import BrandingShareDialog from "@/components/branding/BrandingShareDialog";
const state = vi.hoisted(() => ({ role:'owner', db: {} as Record<string, any[]>, fail:'', inserts: [] as any[], uncertain:false, zeroUpdate:false }));
vi.mock('@/contexts/WorkspaceContext',()=>({useWorkspace:()=>({activeRole:state.role})}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:(table:string)=>{
  let single=false; let inserted:any; let patch:any; const filters: Array<(r:any)=>boolean>=[];
  const q:any={select:()=>q,order:()=>q,eq:(k:string,v:any)=>{filters.push(r=>r[k]===v);return q},is:(k:string,v:any)=>{filters.push(r=>r[k]===v);return q},single:()=>{single=true;return q},maybeSingle:()=>{single=true;return q},insert:(data:any)=>{inserted=data;return q},update:(data:any)=>{patch=data;return q},then:(resolve:any)=>{
    if(state.fail===table)return resolve({data:null,error:{message:'read failed'}});
    if(inserted){state.inserts.push(inserted);const row={...inserted,id:'new',is_active:true,created_at:'2026-09-14',expires_at:'2099-01-01'};state.db[table].push(row);if(state.uncertain){state.uncertain=false;return resolve({data:null,error:{message:'lost response'}})}return resolve({data:row,error:null})}
    const rows=(state.db[table]||[]).filter(r=>filters.every(f=>f(r)));if(patch){if(state.zeroUpdate)return resolve({data:null,error:null});rows.forEach(r=>Object.assign(r,patch))}
    resolve({data:single?rows[0]||null:rows.map(r=>({...r})),error:null});
  }};return q;
}}}));
const mount=()=>render(<BrandingShareDialog open onOpenChange={()=>{}} column="workspace_id" value="a" ownerId="owner"/>);
beforeEach(()=>{state.role='owner';state.fail='';state.inserts=[];state.uncertain=false;state.zeroUpdate=false;state.db={shared_branding_links:[{id:'old',token:'old',user_id:'owner',workspace_id:'a',is_active:true,created_at:'2026-08-16',expires_at:'2099-01-01',views_count:9}],persona:[{id:'p1',workspace_id:'a',label:'A'},{id:'p2',workspace_id:'a',label:'B'}],storytelling:[{workspace_id:'a',title:'Principal',is_primary:true},{workspace_id:'a',title:'Private',is_primary:false}],offers:[]};vi.stubGlobal('crypto',{randomUUID:vi.fn().mockReturnValue('retry-token')});Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:vi.fn().mockResolvedValue(undefined)}})});
it('shows exact old expiry and explicit contents without creating a replacement',async()=>{mount();expect(await screen.findByText(/A · B/)).toBeInTheDocument();expect(screen.getByText(/1 autre/)).toHaveTextContent('Principal');expect(screen.getByText(/Expire le/)).toHaveTextContent('2099');fireEvent.click(screen.getByText('Copier ce lien'));await waitFor(()=>expect(navigator.clipboard.writeText).toHaveBeenCalledWith(expect.stringContaining('/old')));expect(state.inserts).toHaveLength(0)});
it('read failure prevents creation until successful refresh',async()=>{state.fail='offers';mount();expect(await screen.findByRole('alert')).toBeInTheDocument();expect(screen.getByText('Créer un nouveau lien de 30 jours')).toBeDisabled();state.fail='';fireEvent.click(screen.getByText('Actualiser les liens'));await waitFor(()=>expect(screen.getByText('Créer un nouveau lien de 30 jours')).toBeEnabled())});
it('viewer retains read but no create/revoke controls',async()=>{state.role='viewer';mount();await screen.findByText('Copier ce lien');expect(screen.queryByText('Révoquer')).not.toBeInTheDocument();expect(screen.getByText('Créer un nouveau lien de 30 jours')).toBeDisabled()});
it('uncertain insertion resumes the same token without a duplicate',async()=>{mount();await screen.findByText('Copier ce lien');state.uncertain=true;fireEvent.click(screen.getByText('Créer un nouveau lien de 30 jours'));await screen.findByRole('alert');fireEvent.click(screen.getByText('Actualiser les liens'));await waitFor(()=>expect(screen.getByText('Créer un nouveau lien de 30 jours')).toBeEnabled());fireEvent.click(screen.getByText('Créer un nouveau lien de 30 jours'));await waitFor(()=>expect(screen.queryByRole('alert')).not.toBeInTheDocument());expect(state.inserts).toHaveLength(1)});
it('zero-row revoke reports failure and keeps active link',async()=>{mount();await screen.findByText('Copier ce lien');state.zeroUpdate=true;fireEvent.click(screen.getByText('Révoquer'));expect(await screen.findByRole('alert')).toHaveTextContent('Révocation non confirmée');expect(screen.getByText('Copier ce lien')).toBeInTheDocument()});
