import React from "react";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { coachingDatabase } from "./coaching-fixtures";
const mock = vi.hoisted(() => ({ from: vi.fn(), invoke: vi.fn(), stream: vi.fn(), reset: vi.fn(), scope: "w1", toast: { error: vi.fn(), success: vi.fn(), info: vi.fn() }, profile: { prenom: "Test" }, branding: { mission: "Conseil" }, invalidate: vi.fn() }));
vi.mock("@/integrations/supabase/client", () => ({ supabase: { from: mock.from } }));
vi.mock("@/contexts/AuthContext", () => ({ useAuth: () => ({ user: { id: "owner" } }) }));
vi.mock("@/contexts/DemoContext", () => ({ useDemoContext: () => ({ isDemoMode: false }) }));
vi.mock("@/hooks/use-profile", () => ({ useProfile: () => ({ data: mock.profile }), useBrandProfile: () => ({ data: mock.branding }) }));
vi.mock("@tanstack/react-query", () => ({ useQueryClient: () => ({ invalidateQueries: mock.invalidate }) }));
vi.mock("@/hooks/use-workspace-query", () => ({ useWorkspaceReady: () => true, useWorkspaceFilter: () => ({ column: "workspace_id", value: mock.scope }), useWorkspaceId: () => mock.scope, useProfileUserId: () => "owner" }));
vi.mock("@/hooks/use-mobile", () => ({ useIsMobile: () => false }));
vi.mock("@/hooks/use-streaming-invoke", () => ({ useStreamingInvoke: () => ({ invoke: mock.stream, reset: mock.reset }) }));
vi.mock("@/lib/invoke-with-timeout", () => ({ invokeWithTimeout: mock.invoke }));
vi.mock("sonner", () => ({ toast: mock.toast }));
vi.mock("@/components/Confetti", () => ({ default: () => null }));
vi.mock("@/lib/error-tracker", () => ({ trackError: vi.fn() }));
vi.mock("@/components/ui/input-with-voice", () => ({ InputWithVoice: ({ onValueChange, ...p }: any) => <input {...p} /> }));
vi.mock("@/components/ui/textarea-with-voice", () => ({ TextareaWithVoice: ({ onValueChange, ...p }: any) => <textarea {...p} /> }));
vi.mock("framer-motion", () => ({ motion: { div: ({ initial, animate, exit, transition, ...p }: any) => <div {...p} /> }, AnimatePresence: ({ children }: any) => children }));
import CoachingFlow from "@/components/CoachingFlow";
import AuditCoachingPanel from "@/components/audit/AuditCoachingPanel";
import BrandingCoachingFlow from "@/components/branding/BrandingCoachingFlow";
const advanced = { promise_long: "Variante longue", objections: [{ objection: "Cher", response: "En deux fois" }] };
let db: ReturnType<typeof coachingDatabase>;
beforeEach(() => {
  mock.scope = "w1"; vi.clearAllMocks(); Element.prototype.scrollIntoView = vi.fn();
  db = coachingDatabase({ offers: [{ id: "a", workspace_id: "w1", name: "Conseil", ...advanced }, { id: "b", workspace_id: "w1", name: "Formation" }, { id: "c", workspace_id: "w2", name: "Portrait" }], persona: [{ id: "p1", workspace_id: "w1", label: "Instagram", channels: ["instagram"] }, { id: "p2", workspace_id: "w1", label: "LinkedIn", channels: ["linkedin"] }], branding_coaching_sessions: [] });
  mock.from.mockImplementation(db.from);
});
afterEach(cleanup);
const wrap = (node: React.ReactNode) => <MemoryRouter>{node}</MemoryRouter>;
const questions = { data: { questions: [{ numero: 1, question: "Ton offre ?", placeholder: "Réponse" }], intro: "On précise" }, error: null };
const diagnostic = { diagnostic: "À préciser", pourquoi: "Pour comprendre", consequences: [], proposals: [{ label: "Description", field: "description", value: "Nouveau texte" }] };
for (const kind of ["module", "audit"]) {
  it(`${kind}: requires selecting an offer, transmits space/ID, preserves proposals on error and clears explicitly`, async () => {
    mock.invoke.mockImplementation(async (_fn, args) => args.body.phase === "questions" ? questions : { data: diagnostic });
    mock.stream.mockResolvedValue(JSON.stringify(diagnostic));
    const done = vi.fn();
    render(wrap(kind === "module" ? <CoachingFlow module="offers" onComplete={done} onSkip={vi.fn()} /> : <AuditCoachingPanel open onOpenChange={vi.fn()} module="offers" pillarKey="offers" pillarLabel="Offres" pillarEmoji="" onComplete={done} onSkipToModule={vi.fn()} />));
    expect(await screen.findByText("Quelle offre veux-tu travailler ?")).toBeInTheDocument();
    expect(mock.invoke).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole("button", { name: "Conseil" }));
    fireEvent.click(await screen.findByRole("button", { name: "C'est parti" }));
    fireEvent.change(await screen.findByPlaceholderText("Réponse"), { target: { value: "Conseil précis" } });
    fireEvent.click(screen.getByRole("button", { name: "Analyser" }));
    const proposal = await screen.findByDisplayValue("Nouveau texte");
    fireEvent.change(proposal, { target: { value: "" } });
    db.fail("offers", "read");
    fireEvent.click(screen.getByRole("button", { name: /Valider et mettre à jour/ }));
    await waitFor(() => expect(mock.toast.error).toHaveBeenCalled());
    expect(done).not.toHaveBeenCalled();
    expect(screen.getByRole("textbox")).toHaveValue("");
    expect(db.calls.some(c => c.action === "insert")).toBe(false);
    db.recover();
    fireEvent.click(screen.getByRole("button", { name: /Valider et mettre à jour/ }));
    await waitFor(() => expect(db.rows.offers[0].description_short).toBe(""));
    expect(db.rows.offers[0]).toMatchObject(advanced);
    expect(db.rows.offers[1].description_short).toBeUndefined();
    expect(mock.invoke.mock.calls[0][1].body).toMatchObject({ workspace_id: "w1", offer_id: "a" });
    const diagnosticCall = kind === "module" ? mock.stream.mock.calls[0][1] : mock.invoke.mock.calls[1][1].body;
    expect(diagnosticCall).toMatchObject({ workspace_id: "w1", offer_id: "a" });
  });
}
it("branding offers: failed business save cannot complete; reload retries the exact saved proposal", async () => {
  const initial = { question: "Quel nom ?", question_type: "textarea", is_complete: false, placeholder: "Nom", completion_percentage: 0 };
  const final = { question: "", is_complete: true, final_summary: "Offre précisée", completion_percentage: 100, extracted_insights: { offer_name: "Accompagnement", offer_price: "100 €" } };
  mock.invoke.mockResolvedValueOnce({ data: { response: initial } }).mockResolvedValueOnce({ data: { response: final } });
  const view = render(wrap(<BrandingCoachingFlow section="offers" offerId="a" />));
  fireEvent.click(await screen.findByRole("button", { name: "C'est parti →" }));
  fireEvent.change(await screen.findByLabelText("Ta réponse au coaching"), { target: { value: "Accompagnement à 100 €" } });
  db.fail("offers", "update");
  fireEvent.click(screen.getByRole("button", { name: "Suivant →" }));
  await screen.findByText(/La sauvegarde n'a pas abouti/);
  expect(screen.queryByText("✅ Section complète !")).not.toBeInTheDocument();
  expect(db.rows.branding_coaching_sessions[0]).toMatchObject({ offer_id: "a", is_complete: false });
  expect(db.rows.branding_coaching_sessions[0].messages.some((m: any) => m.content === "Accompagnement à 100 €")).toBe(true);
  view.unmount(); db.recover();
  render(wrap(<BrandingCoachingFlow section="offers" offerId="a" />));
  fireEvent.click(await screen.findByRole("button", { name: "On reprend →" }));
  await screen.findByText("✅ Section complète !");
  expect(mock.invoke).toHaveBeenCalledTimes(2);
  expect(db.rows.offers[0]).toMatchObject({ name: "Accompagnement", price_text: "100 €", ...advanced });
  expect(db.rows.offers[1].name).toBe("Formation");
  fireEvent.click(screen.getByRole("button", { name: "Recommencer cette section" }));
  await waitFor(() => expect(db.rows.branding_coaching_sessions[0].archived_at).toBeTruthy());
  expect(db.rows.branding_coaching_sessions[0].messages.length).toBeGreaterThan(0);
});
it("public/space change discards old conversation and ignores late AI responses", async () => {
  let resolve!: (value: any) => void;
  mock.invoke.mockImplementation(() => new Promise(r => { resolve = r; }));
  db.rows.branding_coaching_sessions.push({ id: "legacy", workspace_id: "w1", section: "persona", messages: [{ role: "user", content: "Old" }], is_complete: true });
  const view = render(wrap(<BrandingCoachingFlow section="persona" personaId="p1" />));
  fireEvent.click(await screen.findByRole("button", { name: "C'est parti →" }));
  await waitFor(() => expect(mock.invoke).toHaveBeenCalledTimes(1));
  expect(mock.invoke.mock.calls[0][1].body.context.existing_data.channels).toEqual(["instagram"]);
  view.rerender(wrap(<BrandingCoachingFlow section="persona" personaId="p2" />));
  await screen.findByRole("button", { name: "C'est parti →" });
  await act(async () => resolve({ data: { response: { question: "Ancien contexte", question_type: "textarea", is_complete: false } } }));
  expect(screen.queryByText("Ancien contexte")).not.toBeInTheDocument();
  expect(screen.queryByText("✅ Section complète !")).not.toBeInTheDocument();
  mock.scope = "w2";
  view.rerender(wrap(<BrandingCoachingFlow section="persona" personaId="p2" />));
  await screen.findByText(/Impossible de retrouver la fiche/);
  expect(db.calls.some(c => c.action !== "read")).toBe(false);
});
it("a later AI failure resumes the latest answer, never the previous applied response", async () => {
  const first = { question: "Nom ?", question_type: "textarea", is_complete: false, placeholder: "Nom", completion_percentage: 0 };
  const second = { question: "Prix ?", question_type: "textarea", is_complete: false, placeholder: "Prix", completion_percentage: 25, extracted_insights: { offer_name: "Nom retenu" } };
  mock.invoke.mockResolvedValueOnce({ data: { response: first } }).mockResolvedValueOnce({ data: { response: second } }).mockResolvedValueOnce({ error: { message: "Network" } });
  const view = render(wrap(<BrandingCoachingFlow section="offers" offerId="a" />));
  fireEvent.click(await screen.findByRole("button", { name: "C'est parti →" }));
  fireEvent.change(await screen.findByLabelText("Ta réponse au coaching"), { target: { value: "Nom retenu" } });
  fireEvent.click(screen.getByRole("button", { name: "Suivant →" }));
  await screen.findByText("Prix ?");
  fireEvent.change(screen.getByLabelText("Ta réponse au coaching"), { target: { value: "123 euros" } });
  fireEvent.click(screen.getByRole("button", { name: "Suivant →" }));
  await screen.findByRole("button", { name: "Réessayer" });
  expect(db.rows.branding_coaching_sessions[0].extracted_data.pending_response).toBeNull();
  expect(db.rows.branding_coaching_sessions[0].messages.at(-1).content).toBe("123 euros");
  view.unmount();
  mock.invoke.mockResolvedValueOnce({ data: { response: { ...second, question: "Pour qui ?", extracted_insights: { offer_price: "123 euros" } } } });
  render(wrap(<BrandingCoachingFlow section="offers" offerId="a" />));
  fireEvent.click(await screen.findByRole("button", { name: "On reprend →" }));
  await screen.findByText("Pour qui ?");
  expect(mock.invoke.mock.calls.at(-1)![1].body.messages.at(-1).content).toBe("123 euros");
  expect(db.rows.offers[0].price_text).toBe("123 euros");
});
it("keeps duplicate proposals separately editable until a version is selected", async () => {
  mock.invoke.mockResolvedValue(questions);
  mock.stream.mockResolvedValue(JSON.stringify({ ...diagnostic, proposals: [
    { label: "Courte", field: "description_short", value: "Version A" },
    { label: "Longue", field: "description_short", value: "Version B" },
  ] }));
  render(wrap(<CoachingFlow module="offers" offerId="a" onComplete={vi.fn()} onSkip={vi.fn()} />));
  fireEvent.click(await screen.findByRole("button", { name: "C'est parti" }));
  fireEvent.change(await screen.findByPlaceholderText("Réponse"), { target: { value: "Des variantes" } });
  fireEvent.click(screen.getByRole("button", { name: "Analyser" }));
  fireEvent.change(await screen.findByDisplayValue("Version A"), { target: { value: "Version A corrigée" } });
  expect(screen.getByDisplayValue("Version B")).toBeInTheDocument();
  fireEvent.click(screen.getByRole("button", { name: /Valider et mettre à jour/ }));
  await waitFor(() => expect(mock.toast.error).toHaveBeenCalled());
  expect(db.rows.offers[0].description_short).toBeUndefined();
  fireEvent.click(screen.getAllByRole("radio")[0]);
  fireEvent.click(screen.getByRole("button", { name: /Valider et mettre à jour/ }));
  await waitFor(() => expect(db.rows.offers[0].description_short).toBe("Version A corrigée"));
});
