import { describe, it, expect } from 'vitest';
import { resumeIdea } from '@/lib/resume-idea';
import { buildCalendarContent } from '@/features/creer/build-calendar-content';
import { buildCalendarPostFromIdea } from '@/lib/idea-to-calendar';

const source = { type: 'crosspost', source_type: 'libre', target_channel: 'reel', full_content: 'Script intégral\nPlan final' };
describe('crosspost continuity', () => {
  it('restores an old Reel wrapper without regeneration or loss', () => {
    const resumed = resumeIdea({ titre: 'Reel', format: 'reel', content_data: source });
    expect(resumed?.raw.script).toEqual([expect.objectContaining({ texte_parle: source.full_content })]);
    expect(buildCalendarContent(resumed!.format, resumed!.raw).contentDraft).toContain('Plan final');
  });
  it('accepts the string script actually generated by crosspost', () => {
    expect(buildCalendarContent('reel', { type: 'crosspost', target_channel: 'reel', script: 'Tout le script' }).contentDraft).toBe('Tout le script');
  });
  it('keeps old full_content when moving an idea to calendar', () => {
    const post = buildCalendarPostFromIdea({ titre: 'Reel', format: 'reel', content_data: source });
    expect(post.content_draft).toBe(source.full_content);
    expect(post.story_sequence_detail).toBeTruthy();
  });
});

import { crosspostEnvelope, resumeCrosspost, crosspostText } from '@/lib/crosspost-content';
const versions = {
  linkedin: { full_text: 'Première ligne\nTexte intégral', angle_choisi: 'expert', extension: { original: true } },
  instagram: { full_text: 'Légende complète', slides: [{ title: 'Titre', body: 'Corps complet', photo_url: 'private-image' }], caption: { hook: 'Accroche', body: 'Légende complète', cta: 'Fin' }, visual_html: [{ html: '<b>Titre</b>' }] },
  reel: { script: 'Hook 0-3s\nCut 20s\nConclusion', duration: '30s', cover_text: 'Cover' },
  stories: { story_sequence: [{ text: 'Question', sticker: { type: 'poll', options: ['Oui', 'Non'] }, timing: '10:00', unknown: { keep: 1 } }] },
};
describe('all real structures and provenance', () => {
  for (const key of Object.keys(versions)) it(`generation -> idea -> editor -> calendar -> editor: ${key}`, () => {
    const envelope = crosspostEnvelope({ versions, audit: { score: 8 } }, key, { source_text: 'Source entière', source_files: [{ bucket: 'crosspost-sources', path: 'workspace/a/photo.jpg' }] });
    const format = key === 'stories' ? 'story_serie' : key === 'instagram' ? 'carousel' : key === 'linkedin' ? 'post' : 'reel';
    const idea = { titre: 'Sujet', format, content_data: envelope };
    const editor = resumeIdea(idea)!;
    const calendar = buildCalendarContent(editor.format, editor.raw);
    const reopened = resumeCrosspost(calendar.storyDetail, format)!;
    expect(reopened.raw._crosspost).toEqual(envelope);
    expect(reopened.raw._crosspost.result.versions).toEqual(versions);
    expect(reopened.raw._crosspost.source_files).toEqual(envelope.source_files);
    if (key === 'instagram') expect(reopened.raw.slides).toEqual(versions.instagram.slides);
    if (key === 'stories') expect(reopened.raw.stories[0].sticker).toEqual(versions.stories.story_sequence[0].sticker);
    if (key === 'reel') expect(reopened.raw.script[0].texte_parle).toBe(versions.reel.script);
    expect(calendar.contentDraft).not.toContain('[object Object]');
    expect(buildCalendarPostFromIdea(idea).story_sequence_detail).toBeTruthy();
  });
  it('text-only Instagram stays an editable text, without invented slides', () => {
    const result = resumeCrosspost({ type: 'crosspost', target_channel: 'instagram', text: 'Ancien texte' }, 'carousel')!;
    expect(result.format).toBe('post');
    expect(result.raw.content).toBe('Ancien texte');
    expect(result.raw.slides).toBeUndefined();
  });
  it('edits rich fields without changing original versions or losing new fields', () => {
    const envelope = crosspostEnvelope({ versions }, 'stories', {});
    const resumed = resumeCrosspost(envelope)!;
    resumed.raw.stories[0].text = 'Question corrigée';
    const saved = buildCalendarContent('story', resumed.raw);
    expect(saved.contentDraft).toContain('Question corrigée');
    expect(saved.storyDetail.stories[0].unknown).toEqual({ keep: 1 });
    expect(saved.storyDetail._crosspost.result.versions.stories).toEqual(versions.stories);
  });
  it('structured script arrays and nested story stickers remain readable', () => {
    expect(crosspostText({ script: [{ timing: '0-3s', texte_parle: 'Bonjour', texte_overlay: 'Titre' }] })).toContain('Bonjour');
    expect(crosspostText(versions.stories)).toContain('Oui');
  });
});

it('retains a carousel full_text as its caption and nested Reel sections', () => {
  const raw = resumeCrosspost({ type:'crosspost',target_channel:'instagram',version:{ full_text:'Légende intégrale sans caption',slides:[{title:'Slide',body:'Corps'}] } })!.raw;
  expect(buildCalendarContent('carousel',raw).contentDraft).toContain('Légende intégrale sans caption');
  const nested = { sections:[{ section:'hook',texte_parle:'Hook',timing:'0-3s',media:{url:'keep'} }] };
  const reel = resumeCrosspost({ type:'crosspost',target_channel:'reel',version:{script:nested} })!.raw;
  expect(reel.script).toEqual(nested.sections);
  expect(reel._crosspost.version.script).toEqual(nested);
});
