import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, fireEvent, waitFor, act } from '@testing-library/react';
const mocks = vi.hoisted(() => ({ workspace: 'A', owner: 'owner', role: 'manager', invoke: vi.fn(), rpc: vi.fn(), toast: { error: vi.fn(), success: vi.fn(), info: vi.fn() } }));
vi.mock('@/contexts/AuthContext', () => ({ useAuth: () => ({ user: { id: 'manager' } }) }));
vi.mock('@/hooks/use-workspace-query', () => ({ useWorkspaceId: () => mocks.workspace, useProfileUserId: () => mocks.owner, useWorkspaceReady: () => true }));
vi.mock('@/contexts/WorkspaceContext', () => ({ useWorkspace: () => ({ activeWorkspace: { id: mocks.workspace }, activeRole: mocks.role }) }));
vi.mock('@/lib/invoke-with-timeout', () => ({ invokeWithTimeout: mocks.invoke }));
vi.mock('@/integrations/supabase/client', () => ({ supabase: { rpc: mocks.rpc } }));
vi.mock('sonner', () => ({ toast: mocks.toast }));
vi.mock('@/components/ui/textarea-with-voice', () => ({ TextareaWithVoice: (p: any) => <textarea {...p} /> }));
vi.mock('@/components/RedFlagsChecker', () => ({ default: () => null }));
vi.mock('@/components/BaseReminder', () => ({ default: () => null }));
vi.mock('@/components/AiGeneratedMention', () => ({ default: () => null }));
vi.mock('@/components/AppHeader', () => ({ default: () => null }));
vi.mock('@/components/SubPageHeader', () => ({ default: () => null }));
vi.mock('@/components/calendar/AddToCalendarDialog', () => ({ AddToCalendarDialog: (p: any) => p.open ? <button disabled={p.loading} onClick={() => p.onConfirm('2026-10-02')}>Confirmer la date</button> : null }));
vi.mock('@/components/SaveToIdeasDialog', () => ({ SaveToIdeasDialog: () => null }));
import CrosspostFlow from '@/components/CrosspostFlow';
import LinkedInCrosspost from '@/pages/LinkedInCrosspost';
import { crosspostScope, readCrosspost } from '@/lib/crosspost-persistence';
const output = { versions: { linkedin: { full_text: 'Résultat LinkedIn' }, reel: { script: 'Script Reel complet' } } };
const response = { data: { content: JSON.stringify(output) }, error: null };
beforeEach(() => {
  vi.clearAllMocks(); sessionStorage.clear(); mocks.workspace='A'; mocks.role='manager'; mocks.owner='owner';
  mocks.invoke.mockResolvedValue(response);
  mocks.rpc.mockImplementation(async (_name: any,args: any) => ({ data: { id: args.p_post_id, replayed: false }, error: null }));
});
describe('both crosspost entry points', () => {
  it.each([CrosspostFlow,LinkedInCrosspost])('generates and saves all versions with owner + structure', async Component => {
    const view = render(<Component />);
    fireEvent.change(view.getByPlaceholderText('Colle ton contenu ici...'), { target: { value: 'Ma source' } });
    fireEvent.click(view.getByText('✨ Adapter pour chaque canal'));
    await waitFor(() => expect(view.getByText('Tout planifier')).toBeTruthy());
    fireEvent.click(view.getByText('Tout planifier')); fireEvent.click(view.getByText('Confirmer la date'));
    await waitFor(() => expect(mocks.rpc).toHaveBeenCalledTimes(2));
    const rows = mocks.rpc.mock.calls.map(c=>c[1].p_payload);
    expect(rows.every(r=>r.user_id==='owner' && r.workspace_id==='A')).toBe(true);
    expect(rows[1].story_sequence_detail._crosspost.result).toEqual(output);
    expect(rows[1].story_sequence_detail.script[0].texte_parle).toBe('Script Reel complet');
  });
  it('recovers partial grouped save with identical IDs and no AI call', async () => {
    const view=render(<CrosspostFlow />);
    fireEvent.change(view.getByPlaceholderText('Colle ton contenu ici...'), { target: { value: 'source' } });
    fireEvent.click(view.getByText('✨ Adapter pour chaque canal'));
    await waitFor(() => view.getByText('Tout planifier'));
    mocks.rpc.mockImplementationOnce(async (_: any,args: any) => ({ data: { id: args.p_post_id }, error:null })).mockResolvedValueOnce({ data: { id: 'bad-receipt' }, error:null });
    fireEvent.click(view.getByText('Tout planifier')); fireEvent.click(view.getByText('Confirmer la date'));
    await waitFor(() => expect(mocks.toast.error).toHaveBeenCalled());
    const first=mocks.rpc.mock.calls[0][1].p_post_id;
    fireEvent.click(view.getByText('Confirmer la date'));
    await waitFor(() => expect(mocks.rpc).toHaveBeenCalledTimes(4));
    expect(mocks.rpc.mock.calls[2][1].p_post_id).toBe(first);
    expect(mocks.rpc.mock.calls[3][1].p_post_id).toBe(mocks.rpc.mock.calls[1][1].p_post_id);
    expect(mocks.invoke).toHaveBeenCalledTimes(1);
  });
  it('hides A in B and restores A without generation', async () => {
    const view=render(<CrosspostFlow />);
    fireEvent.change(view.getByPlaceholderText('Colle ton contenu ici...'), { target: { value: 'source A' } });
    fireEvent.click(view.getByText('✨ Adapter pour chaque canal'));
    await waitFor(() => view.getByText('Tout planifier'));
    mocks.workspace='B'; view.rerender(<CrosspostFlow />);
    expect(view.queryByText('Tout planifier')).toBeNull();
    expect((view.getByPlaceholderText('Colle ton contenu ici...') as HTMLTextAreaElement).value).toBe('');
    mocks.workspace='A'; view.rerender(<CrosspostFlow />);
    expect(view.getByText('Tout planifier')).toBeTruthy();
    expect(mocks.invoke).toHaveBeenCalledTimes(1);
  });
  it('does not attach a late A result to a later A visit', async () => {
    let complete!: (v:any)=>void; mocks.invoke.mockReturnValueOnce(new Promise(r=>complete=r));
    const view=render(<CrosspostFlow />);
    fireEvent.change(view.getByPlaceholderText('Colle ton contenu ici...'), { target: { value: 'old' } });
    fireEvent.click(view.getByText('✨ Adapter pour chaque canal'));
    mocks.workspace='B'; view.rerender(<CrosspostFlow />);
    mocks.workspace='A'; view.rerender(<CrosspostFlow />);
    fireEvent.change(view.getByPlaceholderText('Colle ton contenu ici...'), { target: { value: 'new' } });
    fireEvent.click(view.getByText('✨ Adapter pour chaque canal'));
    await waitFor(() => view.getByText('Tout planifier'));
    await act(async()=>complete(response));
    expect(readCrosspost(crosspostScope('manager','A'))?.source.source_text).toBe('new');
    expect(Object.keys(sessionStorage).some(k=>k.includes(':late:'))).toBe(true);
  });
  it.each(['viewer','unresolved'])('prevents generation/write for %s', role => {
    if(role==='viewer') mocks.role='viewer'; else mocks.owner='';
    const view=render(<CrosspostFlow />);
    fireEvent.change(view.getByPlaceholderText('Colle ton contenu ici...'), { target: { value: 'source' } });
    expect(view.getByText('✨ Adapter pour chaque canal')).toBeDisabled();
    expect(mocks.invoke).not.toHaveBeenCalled();
  });
});
