import React from "react";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { coachingDatabase } from "./coaching-fixtures";
const mock = vi.hoisted(() => ({ from: vi.fn(), invoke: vi.fn(), scope: "w1", toast: { error: vi.fn(), success: vi.fn(), info: vi.fn() } }));
vi.mock("@/integrations/supabase/client", () => ({ supabase: { from: mock.from } }));
vi.mock("@/contexts/AuthContext", () => ({ useAuth: () => ({ user: { id: "owner" } }) }));
vi.mock("@/hooks/use-workspace-query", () => ({ useWorkspaceReady: () => true, useWorkspaceFilter: () => ({ column: "workspace_id", value: mock.scope }), useWorkspaceId: () => mock.scope }));
vi.mock("@/lib/invoke-with-timeout", () => ({ invokeWithTimeout: mock.invoke }));
vi.mock("sonner", () => ({ toast: mock.toast }));
vi.mock("@/components/AppHeader", () => ({ default: () => null }));
vi.mock("@/components/SubPageHeader", () => ({ default: () => null }));
vi.mock("@/components/AiGeneratedMention", () => ({ default: () => null }));
vi.mock("@/components/branding/OfferSynthesisCard", () => ({ default: () => null }));
vi.mock("@/components/ui/confirm-dialog", () => ({ useConfirm: () => vi.fn() }));
vi.mock("@/lib/error-tracker", () => ({ trackError: vi.fn() }));
vi.mock("@/components/ui/input-with-voice", () => ({ InputWithVoice: (p: any) => <input {...p} /> }));
vi.mock("@/components/ui/textarea-with-voice", () => ({ TextareaWithVoice: (p: any) => <textarea {...p} /> }));
import OfferWorkshopPage from "@/pages/OfferWorkshopPage";
const base = { id: "a", user_id: "owner", workspace_id: "w1", name: "Conseil", current_step: 1, price_text: "90 €", objections: [{ objection: "Cher", response: "Paiement échelonné", emoji: "€" }], features: { legacy: ["Atelier"] }, promise_long: "Variante", linked_freebie_id: "free", testimonials: [{ quote: "Merci" }] };
let db: ReturnType<typeof coachingDatabase>;
const page = () => <MemoryRouter initialEntries={["/offre/a"]}><Routes><Route path="/offre/:id" element={<OfferWorkshopPage />} /><Route path="/branding/offres" element={<p>Liste des offres</p>} /></Routes></MemoryRouter>;
beforeEach(() => { mock.scope = "w1"; localStorage.clear(); vi.clearAllMocks(); db = coachingDatabase({ offers: [base, { ...base, id: "b", name: "Formation" }] }); mock.from.mockImplementation(db.from); });
afterEach(() => { cleanup(); vi.useRealTimers(); });
it("autosaves a price without rewriting objections, legacy features or advanced values", async () => {
  render(page());
  fireEvent.change(await screen.findByLabelText("Prix"), { target: { value: "120 €" } });
  await waitFor(() => expect(db.rows.offers[0].price_text).toBe("120 €"), { timeout: 2500 });
  expect(db.rows.offers[0]).toMatchObject({ ...base, price_text: "120 €" });
  expect(db.rows.offers[1]).toEqual({ ...base, id: "b", name: "Formation" });
  const writes = db.calls.filter(c => c.action === "update");
  expect(Object.keys(writes[0].payload).sort()).toEqual(["price_text", "updated_at"]);
  expect(await screen.findByText("✓ Sauvegardé")).toBeInTheDocument();
});
it("stays on the step on failure, preserves the draft across reload, then retries", async () => {
  db.fail("offers", "update");
  const view = render(page());
  fireEvent.change(await screen.findByLabelText("Prix"), { target: { value: "150 €" } });
  fireEvent.click(screen.getByRole("button", { name: "Suivant →" }));
  await waitFor(() => expect(mock.toast.error).toHaveBeenCalled());
  expect(screen.getByLabelText("Prix")).toHaveValue("150 €");
  expect(screen.queryByText("✓ Sauvegardé")).not.toBeInTheDocument();
  expect(db.rows.offers[0].current_step).toBe(1);
  view.unmount();
  await act(async () => {});
  db.recover();
  render(page());
  expect(await screen.findByLabelText("Prix")).toHaveValue("150 €");
  fireEvent.click(screen.getByRole("button", { name: "Suivant →" }));
  await screen.findByText("② Le problème que ton offre résout");
  expect(db.rows.offers[0].price_text).toBe("150 €");
  expect(db.rows.offers[0].objections).toEqual(base.objections);
});
it("preserves generated objection responses through next and a later simple edit", async () => {
  db.rows.offers[0].current_step = 6;
  mock.invoke.mockResolvedValue({ data: { objections: [{ objection: "Cher", response: "Nouvelle réponse", emoji: "€" }] }, error: null });
  render(page());
  fireEvent.click(await screen.findByRole("button", { name: "Générer des réponses" }));
  await screen.findByText("→ Nouvelle réponse");
  fireEvent.click(screen.getByRole("button", { name: "Suivant →" }));
  await screen.findByText("⑦ L'angle émotionnel");
  fireEvent.click(screen.getByRole("button", { name: "1. Bases" }));
  fireEvent.change(screen.getByLabelText("Prix"), { target: { value: "200 €" } });
  await waitFor(() => expect(db.rows.offers[0].price_text).toBe("200 €"), { timeout: 2500 });
  expect(db.rows.offers[0].objections[0].response).toBe("Nouvelle réponse");
});
it("never announces or leaves a completed step after a failed synthesis save", async () => {
  db.rows.offers[0].current_step = 7;
  db.fail("offers", "update");
  mock.invoke.mockResolvedValue({ data: { sales_line: "Un conseil précis", before: "Flou", after: "Clair", feelings: ["Confiance"] }, error: null });
  render(page());
  fireEvent.click(await screen.findByRole("button", { name: "Générer la synthèse" }));
  await screen.findByText('"Un conseil précis"');
  await waitFor(() => expect(mock.toast.error).toHaveBeenCalled());
  expect(mock.toast.success).not.toHaveBeenCalled();
  fireEvent.click(screen.getByRole("button", { name: "Terminer" }));
  await waitFor(() => expect(db.calls.filter(c => c.action === "update").length).toBe(2));
  expect(screen.queryByText("Liste des offres")).not.toBeInTheDocument();
  expect(mock.toast.success).not.toHaveBeenCalled();
});
it("restores only dirty fields so a newer server value in another field is preserved", async () => {
  db.fail("offers", "update");
  const view = render(page());
  fireEvent.change(await screen.findByLabelText("Prix"), { target: { value: "300 €" } });
  view.unmount();
  await act(async () => {});
  db.rows.offers[0].name = "Nouveau nom depuis une autre fiche";
  db.rows.offers[0].objections[0].response = "Réponse actualisée";
  db.recover();
  render(page());
  expect(await screen.findByLabelText("Prix")).toHaveValue("300 €");
  fireEvent.click(screen.getByRole("button", { name: "Suivant →" }));
  await screen.findByText("② Le problème que ton offre résout");
  expect(db.rows.offers[0].name).toBe("Nouveau nom depuis une autre fiche");
  expect(db.rows.offers[0].objections[0].response).toBe("Réponse actualisée");
});
