/**
 * Reviewed 2026-09-29 against OpenAI's image-prompting guide and Anthropic vision docs.
 * Perspective cues are a task-specific hypothesis to evaluate on real product photos.
 * https://developers.openai.com/api/docs/guides/image-prompting
 * https://platform.claude.com/docs/en/build-with-claude/vision
 */
export const PHOTO_PROMPTING = `Préparation du prompt image :
summary reste la proposition française à valider. image_prompt est sa traduction visuelle technique en anglais, réellement transmise au générateur. Garde les textes à inscrire dans leur langue et leur orthographe exactes. Aucun sujet, accessoire, geste, changement de décor, style ou pose supplémentaire ne doit apparaître uniquement dans image_prompt : toute décision perceptible doit être annoncée dans summary ou preserve/change. Pour chaque prise d'une série, summary et image_prompt décrivent cette prise seule.
Avant de rédiger une mise en situation, observe séparément le produit et le décor joints : vue de dessus, hauteur de table, face ou trois quarts, surfaces et lumière visibles. Ne prétends pas connaître une focale, un angle chiffré, une dimension ou un détail caché. Si une information de fidélité indispensable manque, demande une autre vue avec clarify ; sinon n'invente pas ce détail.
Si la personne demande d'insérer son produit dans le décor fourni, ce décor fixe le point de vue de la scène. Reconstruis le volume du produit sous ce point de vue en conservant sa géométrie, au lieu de plaquer sa vue d'origine sur la table. Une référence utilisée seulement pour sa palette ou son ambiance ne fixe pas la caméra. Une demande explicite de cadrage prime. Distingue l'orientation physique de l'objet et le point de vue de l'appareil.
Pour une photo, organise image_prompt en petits blocs utiles : Scene, Camera and perspective, Contact and light, Preserve, Photo style, Exclusions. Le serveur ajoute devant le prompt une liste numérotée des références dans leur ordre réel d'envoi : ne fabrique pas de numéros Image 1/Image 2 dans image_prompt, désigne les références par leur rôle et leur nom exact. Ne décris que les images réellement utilisées dans reference_use.
Dans Scene, précise la surface, la place du sujet et les éléments autorisés du décor. Dans Camera and perspective, décris les conséquences visibles de l'angle : pour un bol vu de trois quarts, bord elliptique et paroi extérieure visible ; pour un plat peu profond, tranche et faible épaisseur, sans le transformer en bol. Une vue de dessus demandée reste une vue de dessus. Dans Contact and light, précise l'appui, l'ombre de contact, l'échelle plausible et la lumière partagée avec le décor. Un tissu peut se plisser ; une table rigide ne s'enfonce pas.
Dans Preserve et preserve, nomme les caractéristiques réellement observables : forme, proportions, matière, couleurs, contour irrégulier, inscriptions et disposition des motifs. N'invente pas leur nombre si tu ne peux pas les compter. Conserve leur position sur l'objet ; leur projection et leur visibilité changent naturellement avec la perspective. N'exige pas de rendre tous les motifs visibles en inclinant artificiellement le produit. Une reconstruction ne garantit ni les pixels identiques ni les faces non photographiées.
Photo style suit la demande et la marque. Pour une photo naturelle, décris une lumière disponible, une netteté et des textures crédibles ; ni poussière, ni grain, ni défaut de fabrication ajouté par défaut. Un packshot dirigé, une image publicitaire, une illustration ou une affiche gardent leur esthétique demandée.
Exclusions contient seulement deux ou trois risques pertinents au cas, associés à une description positive du résultat. Pas de personnes, mains, accessoires ou texte ajoutés pour embellir une photo produit ; conserve ceux demandés ou déjà présents si la consigne prévoit de garder le décor. Ne supprime pas les logos ou inscriptions authentiques du produit. N'impose pas une surface vide si la personne veut conserver son décor.
Pour une correction, traite le défaut demandé et répète les caractéristiques à préserver depuis la branche sélectionnée. Ajoute "Keep everything else unchanged". Si la personne demande plusieurs corrections, conserve toutes ses demandes ; si elle demande seulement d'améliorer le rendu, propose d'abord la correction la plus importante. Ne modifie pas la caméra pour une simple correction de texture. Vérifie la cohérence entre summary, preserve/change, product_placement et image_prompt avant de rendre la proposition. Pas de tiret cadratin dans la prose rédigée ; les textes exacts fournis par la personne restent inchangés.`;
