/** Shared by planning, direct vision writing and the question pass. */
export const PHOTO_NARRATIVE_CONTRACT = `
INTENTION AVANT LES SLIDES — PHOTOS ET RÉCIT DE MARQUE
Pars de la demande, de l'objectif s'il existe, de la voix et des faits de marque déjà recueillis, puis examine les photos ensemble. Sans objectif explicite (notamment après onboarding), propose une découverte cohérente de la marque à partir de cette matière ; ne suppose ni vente, ni commentaires, ni récit de fabrication.
Choisis le fil AVANT les titres : intention, point de départ, progression adaptée, promesse de couverture et aboutissement. Le fil peut être une histoire de marque fournie, un choix expliqué, une conviction étayée, une découverte, un usage, une exploration de collection ou une transformation documentée. Aucun arc universel. Pour chaque page, prévois son apport et le lien de sens qui prépare la suivante.
N'étale pas la fiche de marque en rubriques successives (matière, inspiration, usage, offre). Sélectionne une idée directrice dans cette matière et développe-la : le passage suivant précise, explique, illustre ou tire une conséquence de ce qui vient d'être dit. Ce lien doit se comprendre dans les textes publiés, pas seulement dans les notes internes du plan. Une liste explicitement utile reste possible, avec son critère commun clairement annoncé.
Regroupe les informations qui s'expliquent ensemble. N'ajoute pas une slide pour isoler une petite phrase de la biographie, et ne répète pas des photos pour remplir un nombre implicite. Avec une matière courte, préfère moins de pages mais des passages assez développés pour comprendre leur lien. Les photos disponibles et le nombre demandé restent des contraintes à respecter, sans quota de mots mécanique.
Les photos peuvent accompagner un récit de marque sans illustrer chaque phrase : ambiance, présence, écho ou exemple. Leur compatibilité avec le propos suffit ; aucune obligation de décrire chaque image ni d'en extraire une leçon. Les faits de marque confirmés peuvent porter le récit même s'ils ne sont pas photographiés. Une référence visuelle n'est pas une preuve d'un souvenir ou d'une intention artistique.
Sépare trois niveaux : faits explicitement fournis (brief, réponses, histoire de marque), observations visibles et interprétations. Un nom ou une description de bibliothèque peut être automatique : c'est un indice, pas un témoignage. Une photo de main tenant un bol ne prouve pas le façonnage ; une fleur peinte ne prouve pas qu'un pot contient une fleur. Plusieurs objets différents ne documentent pas la fabrication d'un seul. Ne transforme jamais un motif en souvenir d'enfance, une ressemblance en influence revendiquée, ni une mise en scène en résultat client.
La couverture promet ce que le récit tient réellement. Si les images n'attestent pas toutes les étapes, une explication de fabrication reste possible avec des faits fournis, sans prétendre montrer une transformation documentée. Sans ces faits, choisis un autre angle honnête. Conclus à partir de ce qui a été développé et de l'objectif disponible ; aucune question automatique ni appel commercial inventé. La présence d’une offre ou d’un lieu de vente dans le profil n’impose pas de les ajouter en conclusion : ne les utilise que s’ils prolongent ce récit et son intention.
Respecte l'ordre et les associations déjà choisis. Le lien image/texte peut être indirect ; précise alors ce que l'image accompagne sans l'utiliser comme preuve. Les détails visuels servent le placement et la compatibilité, pas une obligation d'écriture sensorielle. Préserve la voix propre à cette marque, jamais un style Nowadays universel.
`;

export const PHOTO_QUESTIONS_CONTRACT = `
Utilise d'abord le sujet, l'objectif, les réponses et le contexte de marque déjà disponibles. Pose zéro, une ou deux questions simples uniquement lorsqu'une information essentielle manque pour écrire honnêtement le récit demandé. Si la matière suffit, retourne questions:[] ; aucun questionnaire obligatoire.
Une question peut porter sur une histoire de marque non visible dans les photos. N'impose aucune référence visuelle dans chaque question et ne présuppose ni souvenir, ni motivation, ni transformation. Ne demande pas de choisir une intention si une proposition prudente peut être tirée du contexte. Si un récit précis manque de faits, demande le fait manquant plutôt que d'inventer. Ne redemande pas ce qui est déjà fourni.
`;
